project:
  type: book
  
book:
  title: "Leaf Energy Balance Tutorial"
  subtitle: "Predicting a leaf's long-term temperature based on eco-evolutionary optimality principles"
  author: "Pascal Schneider"
  date: "2023-08-23"
  page-navigation: true
  chapters:
    - index.qmd
    - 01-motivation.qmd
    - 02-theory.qmd
    - 03-algorithm.qmd
    - 98-next-steps.qmd
    - 99-variables.qmd
    - references.qmd
  search: true
  sharing: [twitter, facebook, linkedin]
  navbar: 
    right:
      - icon: github
        href: https://github.com/padasch/leaf_energy_balance_tutorial
        aria-label: GitHub
  
bibliography: references.bib
csl: global-change-biology.csl

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 4
    grid: 
      body-width: 1000px
      sidebar-width: 250px
      margin-width: 250px
    # code-fold: show
    code-line-numbers: true
    
knitr:  
  opts_chunk:
    out.width: "80%"
    fig.align: "center"

editor: visual

execute: 
  warning: false
  freeze: auto