project:
  type: book
  
book:
  title: "Leaf Energy Balance Tutorial"
  subtitle: "Predicting a leaf's long-term temperature based on eco-evolutionary optimality principles"
  author: "Pascal Schneider"
  date: "2023-08-23"
  page-navigation: true
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-theory.qmd
    - 03-implementation.qmd
    - 04-sensitivity_analysis.qmd
    - 05-test_case.qmd
    - 99-exercise.qmd
    - references.qmd
  search: true
  sharing: [twitter, facebook]
  navbar: 
    right:
      - icon: github
        href: https://github.com/padasch/leaf_energy_balance_tutorial
        aria-label: GitHub
  
bibliography: references.bib
csl: global-change-biology.csl

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    code-fold: show
    

editor: visual

execute: 
  warning: false
  freeze: auto